version: "3"

tasks:
  postgresInit:
    cmds:
      - docker run --name songAPI -p 5430:5432 -e POSTGRES_USER=root -e POSTGRES_PASSWORD=password -d postgres:16-alpine
  createDB:
    cmds:
      - docker exec -it f24c8df71fcd createdb --username=root --owner=root musicDB
  dropDB:
    cmds:
      - docker exec -it f24c8df71fcd dropdb musicDB
  connect:
    cmds:
      - docker exec -it f24c8df71fcd psql --host=localhost --dbname=musicDB --username=musicuser
